### ISSUE TITLE
Case insensitive keywords etc

### ISSUE THREAD

**Issue by Fandangi** [foo123/codemirror-grammar#12]
Hi - great utility. One question - how can I set the keywords, for example, to be case-insensitive ?

**Comment by foo123** [comment]
Hi thanks. Right now there is not an extra option for this, you can define the keywords as regular expressions (instead of simply array of strings) and use case-insensitive flag to make the matches case-insensitive.  This is what you can do right now. 

I will leave this issue open to have it in mind for a future update.

**Comment by foo123** [comment]
Dont forget to add an array of the keywords (as simple text) in autocomplete option in case you want autocompletion as well (plus caseinsensitive option to autocomplete as case-insentitive). For example like the following:

```javascript
"keyword" : {"tokens":"RE::/(keyword1|keyword2|keyword3)\\b/i", "autocomplete":["keyword1","keyword2","keyword3"], "caseInsensitive":true}
```
