### ISSUE TITLE
Autocomplete not work

### ISSUE THREAD

**Issue by marcosvega91** [foo123/codemirror-grammar#3]
Hi, I have download your project and I open the web page with the javascript-recursive grammar that has the autocomplete set to true but It doesn't work why?

**Comment by foo123** [comment]
Hi, i'm not sure about that, i'll check it out and get back

**Comment by foo123** [comment]
Hi there, i searched around the codebase and it seems this feature is not implemented by default for codemirror. To be precise, codemirror-grammar extracts the keywords from the grammar, but autocomplete hint for codemirror needs extra helper which is not added by default by the codemirror-grammar add-on. The functionality works for ace-grammar (and it is there in codemirror-grammar, but not implemented as helper). Plus i think CodeMirror has made some changes in the hint add-on.

In any case it is going to be added (as explicit implementation), maybe in next update.

Uploaded new CodemirrorGrammar version (0.12) which has some issues fixed, some changes plus makes grammar specification easier (more BNF-like). i leave this issue open to have it in mind.

Thank you

**Comment by foo123** [comment]
Uploaded v. 1.0 with full supoort for BNF-like syntax notation and fixed tag matching actions

**Comment by ExoticObjects** [comment]
I only vaguely understand your response to this issue... What are the chances of you implementing autoCompletion in your examples?

**Comment by foo123** [comment]
The functionality is not implemented for codemirror (but is implemented in the related add-on for ace-grammer to get an example). The keywords are indeed extracted from the grammar, but one needs to delve into codemirror' hint helper to be able to implement the functionality. As a feature it should be added, however due to other work cannot add it right now (maybe in near future, not sure). If you want to undertake this task of adding this feature (getting help from ace-grammar addon), you would have to see how codemirror hint addon works and add a helper in the generated grammar to display associated keywords

**Comment by foo123** [comment]
Keyword autocomplete from grammar helper is added in version [2.1.1](https://github.com/foo123/codemirror-grammar/releases/tag/2.1.1)

Live demo [here](http://foo123.github.io/examples/codemirror-grammar/) (make sure 2.1.1 version is used/refreshed)
