### ISSUE TITLE
grammar-scheme.html is incorrect in v2.3.0

### ISSUE THREAD

**Issue by red-eco** [foo123/codemirror-grammar#4]
grammar-scheme.html is incorrect in v2.3.0

I guess scheme.js needs some thing like this at line 69

//"combine": false,
"combine-before": "\\s, (, ), [, ]",
"combine-after":  "\\s, (, ), [, ]",

**Comment by foo123** [comment]
yes, dont use v. 2.3.0 it is in progress, (actually eventualy it is going to be 2.5.0 or sth as many changes/new features are already added), use one of the released versions 2.2.0 (or lower)

**Note:** (almost all) newer versions (should) have backwards compatibility to the grammar specification (or in other words the grammar spec should be self-contained and detailed as possible), after all that is the point of using a specification, to be re-usable, however some experimental features (like actions etc.. which are still in progress) might need you to tweak some points here and there in the grammar(s) you use (rarely but it might be)

**Comment by foo123** [comment]
v. 2.5.0 (a pre-release as for now) is released, you can try it, 

it has new features,
some typos, fixes
optimisations

**Comment by red-eco** [comment]
It works better than v2.2.0 now.
Thanks!

**Comment by foo123** [comment]
Good, updated the `2.5.0` pre-release tag with 2 latest commits (in case you missed that)

Eventualy will create a full release `2.5.0` out of this (note that in the code the version number is `2.5.0` even in prelease, so check for dates if this is a problem)

**Comment by red-eco** [comment]
I decide to use ace for my first release,
because codemirror lack Indent Guides and Code Folding(both mark begin and
end)

Could you check this work?

editor.setOptions({
            enableBasicAutocompletion: true,
            enableLiveAutocompletion: true,    // No Work!
            enableToggleCommentLines: true,
            enableToggleCommentBlock: true
        });

**Comment by foo123** [comment]
i have added the scheme grammar to [ace-grammar](https://github.com/foo123/ace-grammar/blob/master/test/grammar-scheme.html) as well (after all it is just a style model change nothing else). Se how the [demo.js](https://github.com/foo123/ace-grammar/blob/master/test/demo.js#L10) sets-up code folding and autocompletion.

**note** that currently `*-grammar` code folding with `markbeginend` is slower than `markbegin` due to the way the `fold` model is specified and works (it checkes for begin-fold only, so end-fold is simulated from begin-fold). It should not be a trouble but if you have issues switch to `markbegin`. Also the way the (current)  `ace` editor works seems to me to be a little slower than the way the (current) `codemirror` editor works

**Comment by red-eco** [comment]
autoCloseBrackets is easy to codemirror

I set session.setBehavioursEnabled(true) in demo.js in ace,
but it do not work.

Do you have a way to achieve autoCloseBrackets in ace?

**Comment by foo123** [comment]
hmm, no not at this time. This is additional behaviour each mode implements by itself (or extends another one in case it is same). As is stated behaviours are ACE defaults (meaning using a default mode behaviour, in this case text mode, which does not implement much). A way is researched in order to add behaviours in the specification (see modularity and future directions, along with smart indentation and token matching, eg brace matching). Else all these are just defaults which in most cases do nothing
