### ISSUE TITLE
Sample grammar for markdown (or other lightweight syntax)

### ISSUE THREAD

**Issue by rastapopougros** [foo123/codemirror-grammar#5]
Hello, 
do you know if there is an example of a grammar syntax for markdown or any other lightweight markup ?

I want to describe a grammar for another lightweight syntax, but all examples is for programming languages (exept XML, but there is always start/end tags around, whereas in lightweight syntax there is only 1 or 2 char starting the line, for ex in lists, etc).

So if you have info on that…

Thanks in advance.

**Comment by foo123** [comment]
You can take the xml markup grammar as example and do a variation. Markdown uses tags as well just simpler (e.g `[link]`). Try this approach and let me know how it goes

**Comment by foo123** [comment]
To give you a further hint try the following:

1. links, images can be modelled similarly to xml tags by using `[` and `]` and `![`and `]` as start/end tags
2. bold, italic can be moddled either as blocks (easier) or as tags with `*`, `**` or `_`, `__` delimiters/tags
3. code can be modeled as block with `'` and `'` delimiters
4. headers can be modeled as sequences that start with a number of `#` characters
5. lists ar not necessary to model in markdown but if you want you can modle them as either a numeric or `*` followed by a dot a space and text

Hope these help

**Comment by rastapopougros** [comment]
Thanks for your tips. I will try to start from the XML grammar.

Few additional questions : 

1) Is there a way to mix grammars ? To use one or more grammars inside an other, or to use multiple modes at once ? Because, for ex, in the official markdown mode, it uses the other xml mode in addition (so it colors also html code).

2) Is there a way, in the grammar declaration, to use or link with some CodeMirror functionalities ? That, for ex, the purpose of declaration for *lists* : not only for syntax color : in the official markdown mode, when you start a list and press Enter, it automatically continues the list (there is a CM plugin for that but the mode have to use it, I suppose).

**Comment by foo123** [comment]
Well

1. Yes grammars can be mixed (after all they are just json-like objects) and merged as js objects. However this is **not the same** as mode multiplexing (*a-la codemirror*) but can provide similar functionality. But since the final resul is a valid codemirror mode one can use the codemirror mode multiplex functionality as any other mode to multiplex different modes (for example, this is how [contemplate grammar mode works](http://foo123.github.io/examples/contemplate/))

2. Some things that codemirorr modes can do (e.g auto-indent and similar) are currently not implemented in the add-on. But they are **indeed scheduled to be implemented** when i have an understanding of a generic way to do it. Other functionalities are available either via codemiror itself (e.g folding, comments toggle etc..) and/or can be available via overriding final mode methods with your own. So for the example "* in the official markdown mode, when you start a list and press Enter, it automatically continues the list*" i would say no, such functionality is not available in the specification (however it is possible nje can add it via custom methods, but it is rather advanced coding)
