### ISSUE TITLE
Getting context for autocompletion

### ISSUE THREAD

**Issue by snipervld** [foo123/codemirror-grammar#6]
Hi. I'm currently writing grammar for one language using CodeMirror Grammar and it's awesome!
Now, i'm implementing autocompletion hints.
Ex, type "SELECT * FROM" -> Press "Space" -> Will show list with keywords:
* Table1
* Table2
* FooTable
and others

I implemented this behaviour (with lint-"magic"), but HOW to do this after press "Space" without typing any char? In particularly, how to get expected keyword groups (for example, grouped by `meta` property)?

lint-"magic": when user types, for example, "SE", hint-interceptor call editor.performLint() to get all errors and parses this list to understand current "context" (appropriate words). (i.e. keyword "SET" cannot be at the start of SQL statement, only "SELECT" (and others))
Thanks! ~~Sorry for my bad English...~~

**Comment by foo123** [comment]
Hi and thanks. This is not possible with the default implementation since the hint popup will ap;pear if there is at least one character https://github.com/foo123/codemirror-grammar/blob/master/src/main.js#L113. However you can achieve both of what you need 

1. Hints without typing characters
2. Only hints for given context

By overriding parser autocompleter  here https://github.com/foo123/codemirror-grammar/blob/master/src/main.js#L113 and here https://github.com/foo123/codemirror-grammar/blob/master/src/main.js#L301 with custom methods to fetch the hints you need based on circumstances.  You can use the existing methods as reference and roll-out your own logic

**Comment by snipervld** [comment]
I will try to do this, but open codemirror grammar test-place at
http://foo123.github.io/examples/codemirror-grammar/
Type string "function" in "Sample Code to be highlighted:" text block (only string "function")
How to get expected words,keywords, etc. without using that hacky solution (which doesn't work for zero symbols, because there isn't errors, that can be grabbed by my autcompleter)

**Comment by foo123** [comment]
Hints are supposed to be provided for some initial text. This is a default behaviour and this is how is implemented. You can get functions as hints when you type the keyword `function` by overriding the autocompleter. Then you can use your own method and can use `codemirror` itself in your method to get previous token and its type and fetch hints that match the type.

So for your example since the keyword is `function`, in your custom method you can get the token value (=`"function"`) and token type (=`"keyword"`) and based on these (assuming your grammar already defines some default functions as tokens) you can present only the hints which have "function" as meta.

It is not hacky solution, it is a way to override default behaviour in a clean and modular way. The parser class is  available public and can be overriden/extended exactly for these reasons

If you try this and have any problems let me know.

**Comment by foo123** [comment]
If that helps see how codemirror itself implements context-specific hints (e.g [for javascript](https://github.com/codemirror/CodeMirror/blob/master/addon/hint/javascript-hint.js)) and use similar.

Codemirror Grammar is a generic tool which and does not use pre-assumtions about the code to be highlighted except what is given in the grammar specification, so these language specific features are not implemented out-of-the-box. But one can easily incorporate them via overriding default methods.

**Comment by snipervld** [comment]
I have an idea: before passing json-grammar to library, parse it: add to every keywords group (`"autocompletion" : true`) property `expected` with list of expected words. (I.e., `"expected" : ["and", "funcName"] `
What are you thinking? Will it work

**Comment by foo123** [comment]
Well if you have an idea of a generic way to add context-specific hints in the grammar specification let me know or even better you can try a pull request. Always interested.

In any case it is easier to provide this extra functionality via a custom method if needed, as needed.

**Comment by snipervld** [comment]
Offtop: how to get previous token in the codemirror?
E.g. if I type "select w" and press ctrl+space, how to get "select" token? I know, that method `getTokenAt` exists, but how to get previous token?
Thanks and sorry for offtop

**Comment by snipervld** [comment]
And I almost implemented that idea (about grammar-independent code completion)

**Comment by foo123** [comment]
You can either search char-by-char and while not empty character move the cursor back and get the token at that final position ("select") and/or yopu can get the token at cursor and from gatLineTokens, find the token at the next previous position

**Comment by foo123** [comment]
i think the best way to implenet a generic version hinting based on previous token is to add it as an option in the options of the autocompleter (like the `prefixMatch` option and so on..) see setting `autocompleter` options here https://github.com/foo123/codemirror-grammar#how-to-use

**Comment by snipervld** [comment]
I have some troubles with getting previou token:
How to get *Name* of the previous token?
for example:
Lex: {{ "is-keyword" : "is"},
{"when-keyword": "when"}}
Syntax:{
root: "is-keyword when-keyword"
}
Supposing, we are staying on word "when". With help of cycle `while`, we move on the token "is".
`getTokenAt` returns something like this: `{ word : "IS", type: "keyword" }`. Can we get codemirror-grammar's name of this (previous) token?

**Comment by foo123** [comment]
Yes codemirror itself will return the **style** of the token as its type, instead of the grammar **name/type** of the token.  For now try this simple workaround:

replace this [line](https://github.com/foo123/codemirror-grammar/blob/master/src/main.js#L254) with:

```javascript
var tokenO = CMode.$parser.token( pstream, state );
var token = new String(tokenO.type);  // create a dynamic string to add more properties
token.type = tokenO.id; // this is the grammar name of the token
// ..
return token;
```

Then in your autocompleter code, try to check if token.type is passed along

**Comment by foo123** [comment]
i would suggest to submit a request in codemirror to accept an object as a token instead of just a style string, so more information can be passed along as needed, if needed.

In order for existing modes to continue working there can be a simple test in codemirror, that if the returned token is a string, wrap it in an object like:

```javascript
//..
var token = current_mode.getToken(/*..*/);
if ( "string" === typeof token ) token = {type:token};
// ..
```

This would solve some problems with additional token information

**Comment by snipervld** [comment]
Breaking News (what i'm doing till now): I implemented Syntax Tree, which used to predict expectable words (maybe, it's somehow impemented in this lib, I'm a little confused in the code :) ). Code, that i wrote, parses `Syntax` part of the grammar and modify almost every terminal int the `Lex` part
(e.g. `"select-parameter" {
"autocompletion" : true,
"tokens" : ["Field1", "Field2", "FieldFoo"],
"expected" : ["from-type"],
"expected-tokens" : ["FROM"]
}`)

**Comment by foo123** [comment]
Nice, but i still think the best solution is an option in the autocompleter (to fetch the context of a token) plus a custom callback to filter the keywords based on context and so on..

**Comment by snipervld** [comment]
hello, sorry for late answer: i tried to get context (like you said), and found properties `context` and `in-context`, but i didn't realized, how they worked. (saw javascript and xml grammars, but no luck)
And: what is `getTokenAt(....).state.ctx`? It always equals `null`.

**Comment by foo123** [comment]
The properties `context` and `in-context` are completely different than what you need and refer to actions (like `unique identifier action`) that only takes place inside a given context (for example to check `unique xml tag property names` one creates a new context when a tag token opens and closes it when a tag closes).  Similarly `..state.ctx` stores that information but is reset when not needed, thus you will most probably find `null` there

**Comment by foo123** [comment]
Hi there, i thought about another way to add context-specific autocompletion without adding extra data/information in the grammar (but still using an extra option in the autocompletger e.g `withContext` or `inContext`).

The method is as follows, the autocompleter can get the parser state at the point of the autocompletion, the parfser state keeps a stack of the **current symbol and next expected symbol(s)** that can occur at that place (if there are any of course). Then:

1. If there are no syntax rules active at that point then the suggestions are given based on all available suggestions (as it happens now)
2. Else the suggestions are given based on the expected symbol(s) which contain keywords marked as autocomplete

This probably requires a slight change in the parser to be able to fetch the expected symbols from a state. Otherwise it is straightforward and **does not require any extra info than the grammar itself** (and of course keywords marked as `autocomplete`)

**Comment by snipervld** [comment]
Hi, sorry for late answer, I done autocompletion with approach, similar to you :) (get previous token, get last item of the `stack` and parse tokenizer's tree to get expected terminals) (but ignore `autocomplete` property)

I will write my code in another git project, because I made changes in the complete/compiled file (it's crazy, I know :))

**Comment by foo123** [comment]
Yes sounds similar, the point isthat the grammar knows what symbol(s) are to be xpected in each case (if some rules have been defined of course). So this information need not be added extra, as it is already there, just needs to be extracted appropriately to be used. At that point a method which traverses the expected symbol(s) and extracts keywords for autocompletion can be added. Then the rest autocompletion can proceed as usual only this time with the new set of suggestions. Again having an option to do that is good, since one might nor want such functionality (which is kind of slower also). Plus a custom callback can also be an option for even more customised autocompletion.

The trick here to achieve full context-specific autocompletion is that one will have to split the keywords marked for autocompletion (even if they might have the same style/type) by grouping them in different groups according to what position/role in syntax rules they apply. The rest is straightforward.


If you have sth working and you want to share or pull feel free to do that. i'm working on it as well along the lines i mentioned.

**Comment by foo123** [comment]
Have added context-sensitive autocompletion directly from the grammar in version 3.0.0 (along with some other features and optimisations).

The "autocomplete" option works similarly only it can also accept an array of autocompletions instead of being boolean (in case the "tokens" option is a regular expression etc..)

There is a new option in autocompleter "inContext" which enables context-sensitive autocompletion (false by default).

Closing this issue, if you have any qustions, open a new one.

Cheers!

**Comment by foo123** [comment]
Have another update 3.1.0 

with some corrections in context-sensitive autocompletion, 

plus new feature: `positive` /' `negative` `lookahead` tokens (resolving ambiguities, provide even more context-sensitive parsing).

**Comment by snipervld** [comment]
Hi. Sorry, I forget to share my code, because I was ill. Thanks for update, I will try it.

**Comment by foo123** [comment]
No problem, let me know how it goes with your use case. Cheers!

**Comment by snipervld** [comment]
Hello. I recently tryed new CodeMirrorGrammar 3.1.0. Works great!

But I have some problems with codecompletion (in short, if at least 1 token is a prefix of 2 or more tokens, then autocompletion "going crazy")

Grammar to test (assume, that *inContext* = *true*):
```json
{
 "RegExpID": "RE::",
 "Extra": {
  "fold": "and"
 },
 "Style": {
  "keyword": "keyword"
 },
 "Lex": {
  "Entity": {
   "autocomplete": true,
   "meta": "ParamName",
   "tokens": [
    "EntityAttribute",
    "RE::/EntityAttribute/i"
   ],
   "msg": "Expected: ParamName",
   "ci": true
  },
  "Condition": {
   "autocomplete": true,
   "meta": "ParamName",
   "tokens": [
    "Condition",
    "RE::/Condition/i"
   ],
   "msg": "Expected: ParamName",
   "ci": true
  },
  "EntityAttribute": {
   "autocomplete": true,
   "meta": "Workflow EntityAttribute-identifier",
   "tokens": [
    "#MAIN",
    "#MAIN1",
    "#MAIN2",
    "#x",
    "#ddss",
    "RE::/#MAIN/i",
    "RE::/#MAIN1/i",
    "RE::/#MAIN2/i",
    "RE::/#x/i",
    "RE::/#ddss/i"
   ],
   "msg": "Expected: Workflow EntityAttribute-identifier",
   "ci": true
  },
  "ConditionAttribute": {
   "autocomplete": true,
   "meta": "Workflow Condition-identifier",
   "tokens": [
    "#New,NewID",
    "RE::/#New,NewID/i"
   ],
   "msg": "Expected: Workflow Condition-identifier",
   "ci": true
  }
 },
 "Syntax": {
  "keyword": "(Entity EntityAttribute|Condition ConditionAttribute).keyword"
 },
 "Parser": [
  [
   "keyword* $"
  ]
 ]
}
```

**Comment by foo123** [comment]
Hi,

first there are a couple of options in autocompleter, e.g

```javascript
"prefixMatch": true|false // whether to try to match based on prefix of token (if exists) and on current cursor position
"caseInsesitiveMatch":true|false, // whether provide a match regarldess of case or not
"inContext":true|false  // whether to try a match extracted from grammar and current rules applying (if any)
```

Apart from that, your example grammar needs correction in the sense that `"autocomplete"` option accepts a boolean (`true` / `false`) but only if the `"tokens"` option are keywords (**and not regular expressions** as in your example). In case the tokens are regular expressions then the `"autocomplete"` option can also accept an array of keywords for autocompletion, that is what you should do, even though i dont see the need for using regular expresions in the tokens

Apart from that you can also use the `"caseInsensitive"` or `"ci"` flag to indicate for both tokens and autocompletions that are case-insesitive (`false` by default).

For example try these corrections in your grammar:

```javascript
{
 "RegExpID": "RE::",
 "Extra": {
  "fold": "and"
 },
 "Style": {
  "keyword": "keyword"
 },
 "Lex": {
  "Entity": {
   "autocomplete": true,
   "meta": "ParamName",
   "tokens": [
    "EntityAttribute" // token is just keyword, same can be used for autocompletion
   ],
   "msg": "Expected: ParamName",
   "ci": true // case-insensitive
  },
  "Condition": {
   "autocomplete": true,
   "meta": "ParamName",
   "tokens": [
    "Condition"
   ],
   "msg": "Expected: ParamName",
   "ci": true
  },
  "EntityAttribute": {
   "autocomplete": true,
   "meta": "Workflow EntityAttribute-identifier",
   "tokens": [
    "#MAIN",
    "#MAIN1",
    "#MAIN2",
    "#x",
    "#ddss"
   ],
   "msg": "Expected: Workflow EntityAttribute-identifier",
   "ci": true
  },
  "ConditionAttribute": {
   "autocomplete": true,
   "meta": "Workflow Condition-identifier",
   "tokens": [
    "#New,NewID"
   ],
   "msg": "Expected: Workflow Condition-identifier",
   "ci": true
  }
 },
 "Syntax": {
  "keyword": "(Entity EntityAttribute|Condition ConditionAttribute).keyword",
  "start": "keyword* $"
 },
 "Parser": [  ["start"]  ]
}
```

If your tokens need to be regular expresions then provide the keywords for autocompletion as an array in the `"autocomplete"` option (for each token to be autocompleted).

Open another issue if you are having further issues, as this has been addressed and closed

**Comment by snipervld** [comment]
1 Question, related to autocompletion: How to find out, that we "stay" at start of the code, e.g. before first token. I need it to push inital words into autocompetion list, because now autocompleter adds everything if it is at the beginning of the text

**Comment by snipervld** [comment]
Answer my question myself: 
```js
// End of the "autocomplete" function
        return {
            is_start: list.length === parser.$grammar.$autocomplete.length,
            list: list,
            from: CodeMirror.Pos( cur.line, start ),
            to: CodeMirror.Pos( cur.line, end )
        };
```

Just added property **is_start**, but it seems a bit hacky...

**Comment by foo123** [comment]
Please open another issue with the new question to answer there. The reason for this issue has been addressed. if ctx-autocompletion has bugs or needs new features, open a new issue. Lets not bloat this one further.
